### ISSUE TITLE
AnimatorSet leaking

### ISSUE THREAD

**Issue by youfacepalm** [tommybuonomo/andrui#1]
Hey, thanks for the awesome library. It looks like the **AnimatorListenerAdapter** is leaking the entire activity / fragment when using `BounceLoading` view. Currently I am solving this by having a public `onDestroy` method as below and calling it in the onDestroy lifecycle method of Activity / Fragment

```
 public void onDestroy(){
        if(mCircleAnimator != null){
            mCircleAnimator.end();
            mCircleAnimator.removeAllListeners();
            mCircleAnimator = null;
        }
  }
```

**Comment by tommybuonomo** [comment]
Hi youfacepalm!

Thank you for considering my library. You're right, even if an Activity/Fragment is destroyed, the `mCircleAnimator` is not ended and continue to execute in background. 

I find a better solution than relay the `onDestroy` method of the activity to the `CircleLoading` view by redefining the `onDetachedFromWindow` method of the CircleLoading Layout. I will fix this issue quickly and update the repository.

Thanks a lot for reaching out!

**Comment by tommybuonomo** [comment]
Done

**Comment by youfacepalm** [comment]
The pleasure is mine. Glad to be able to contribute to such a wonderful library!
